apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    kanzal: Qalandri
spec:
  containers:
  - name: mysql-container
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_DATABASE
      value: mydb
    - name: MYSQL_USER
      value: noman
    - name: MYSQL_PASSWORD
      value: nomanpass
    - name: MYSQL_RANDOM_ROOT_PASSWORD
      value: '1'


---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    kanzal: Qalandri
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
