apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  labels:
    noman: yousaf
spec:
  containers:
  - name: wordpress-container
    image: wordpress
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: my-service
    - name: WORDPRESS_DB_USER
      value: noman
    - name: WORDPRESS_DB_PASSWORD
      value: nomanpass
    - name: WORDPRESS_DB_NAME
      value: mydb


---
apiVersion: v1
kind: Service
metadata:
  name: wp-service
spec:
  type: NodePort
  selector:
    noman: yousaf
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000
